version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # UI port
      # - "6831:6831/udp" # Agent port
      # - "6832:6832/udp" # Agent compact thrift port
      # - "5775:5775/udp" # Agent compact protobuf port
      # - "5778:5778" # Agent HTTP sampling port
      - "4318:4318"
      - "14268:14268"
      - "4317:4317" 
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411 # Zipkin port
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - jaeger-net
networks:
  jaeger-net:
    driver: bridge
